version: "3.8"
services:
  redis:
    image: redis:latest
    ports: 
    - '6379:6379'

  next-koa:
    build: .
    depends_on:
      - redis
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    volumes:
      - ./:/web/next-koa/

